function index = get_class_index(class_str)
classes = [string('background'), string('aero'), string('bike'), ...
    string('bird'), string('boat'), string('bottle'), ...
    string('bus'), string('car'), string('cat'), ...
    string('chair'), string('cow'), string('table'), ...
    string('dog'), string('horse'), string('motorbike'), string('person'), ...
    string('plant'), string('sheep'), string('sofa'), ...
    string('train'), string('tv')];
for i = 1:length(classes)
    if classes(i) == class_str
        index = i;
        break
    end
end